create table if not exists settings (
  key text primary key,
  value text not null
);

create table if not exists qualification_rules (
  key text primary key,
  value text not null,
  description text not null
);

create table if not exists teams (
  id bigint generated by default as identity primary key,
  name text not null,
  short_name text not null,
  primary_color text not null,
  secondary_color text not null,
  logo_kind text not null,
  sort_order integer not null
);

create table if not exists players (
  id bigint generated by default as identity primary key,
  team_id bigint not null references teams(id) on delete cascade,
  slot_number integer not null,
  name text not null default '',
  is_empty boolean not null default false,
  unique (team_id, slot_number)
);

create table if not exists fixtures (
  id bigint generated by default as identity primary key,
  round_number integer not null,
  match_number integer not null,
  kickoff_at timestamptz not null,
  venue text not null,
  home_team_id bigint not null references teams(id),
  away_team_id bigint not null references teams(id),
  home_score integer,
  away_score integer,
  status text not null default 'Scheduled'
);

create index if not exists idx_players_team_slot on players (team_id, slot_number);
create index if not exists idx_fixtures_kickoff on fixtures (kickoff_at);
